### ISSUE TITLE
MVP 1: User Auth

### ISSUE THREAD

**Issue by juliawang105** [TheSethness/viewTube#3]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [ ] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by PersephoneQueenOfFlowers** [comment]
I'm ready for review of the auth phase checklist. 
https://viewtube2021.herokuapp.com/#/

**Comment by juliawang105** [comment]
- Clear errors between the sign up/ log in forms
- Capitalize `log in ` on the form 
- no errors displayed when an email is not entered for the signup form 
- Add hovering to all buttons on the forms and navbar (for `logout`)
- Sign up form should have a link to login and vice versa 
- The sidebar still displays `login` after a user has logged in 

* Eventually, the index page and the search bar should not be using YouTube's API.

**Comment by PersephoneQueenOfFlowers** [comment]
Great stuff, Julia. Thx for the feedback. I've got the vids pulling down now from AWS. Different vids on a different page with rails. I'm working right now to get the react front-end to show those AWS-served vids. But be assured, I'm already pulling those vids down. Working on this other stuff today.

**Comment by PersephoneQueenOfFlowers** [comment]
ok, I've corrected all of these bullets except for the one with youtube. 

On that one, I have set up AWS and stored vids up there. I've pulled them down and am displaying them with rails on a separate route; but am working now to display them with React and just getting around to retooling the search function to search my videos instead of youtube's videos.
